enableAccessInfo: false
disable_service_register: true
server_addr: 0.0.0.0:8888
service_info:
  service_name: simple_service
  version: 0.0.1
  tag: dev
  scheme: http
grpc_config:
  max_msg_size: 1048576
  max_concurr: 10000
  ent_streams: 1024
