kind: pipeline
type: docker
name: main

platform:
  os: linux
  arch: amd64

workspace:
  base: /data/drone-go
  path: src/git.xiagaogao.com/coffee/boot

clone:
  depth: 1

volumes:
  - name: pkgdeps
    host:
      path: /data/drone/gocache/pkg
  - name: data
    host:
      path: /data/drone

steps:
  - name: build
    image: golang:1.16
    pull: if-not-exists
    environment:
      GOPROXY: https://goproxy.cn,direct
      GOPRIVATE: git.xiagaogao.com
      GOSUMDB: sum.golang.google.cn
      CGO_ENABLED: 0
    volumes:
      - name: pkgdeps
        path: /go/pkg
      - name: data
        path: /data
    commands:
      - ln -s /data/gitconfig ~/.gitconfig
      - go build -v
    when:
      branch:
        include:
          - feature/*
          - master
          - develop
      event:
        include:
          - push
          - pull_request
  - name: slack
    image: plugins/slack
    settings:
      webhook: https://hooks.slack.com/services/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
      channel: dev
      link_names: true
      template: >
        {{#success build.status}}
          build {{build.number}} succeeded. Good job. <@john.doe>
        {{else}}
          build {{build.number}} failed. Fix me please. <@channelname> <@someone>
        {{/success}}
