kind: pipeline
type: exec
name: default

platform:
  os: linux
  arch: amd64

workspace:
  base: /root/drone-go
  path: src/git.xiagaogao.com/coffee/boot

steps:
  - name: build
    pull: if-not-exists
    environment:
      GOROOT: /root/go
      GOPATH: /root/drone-go
      GOPROXY: https://goproxy.io
      GOPRIVATE: git.xiagaogao.com
      GOSUMDB: sum.golang.google.cn
    commands:
      - go build
      - go test
    when:
      branch:
        - master
        - feature/*
      event:
        - push
