kind: pipeline
type: exec
name: default

platform:
  os: linux
  arch: amd64

workspace:
  path: /data/drone/coffee/boot/src

steps:
  - name: linter
    commands:
      - mkdir -p /data/drone/coffee/boot/src
    pull: if-not-exists
    environment:
      GOPROXY: https://goproxy.io
      GOPRIVATE: git.xiagaogao.com
      GOSUMDB: sum.golang.google.cn
    volumes:
      - name: cache
        path: /data/drone/go
  - name: build
    pull: if-not-exists
      environment:
        GOPROXY: https://goproxy.io
        GOPRIVATE: git.xiagaogao.com
        GOSUMDB: sum.golang.google.cn
      volumes:
        - name: cache
          path: /data/drone/go
    commands:
    - go build
    - go test
    when:
      branch:
      - master
      - feature/*
      event:
        - push
