

kind: pipeline
type: exec
name: build

platform:
  os: linux
  arch: amd64

workspace:
  base: /root/drone-go
  path: src/git.xiagaogao.com/coffee/boot

#clone:
#  disable: true
#  depth: 50

steps:
#  - name: clone
#    commands:
#      - git clone https://github.com/octocat/hello-world.git .
#      - git checkout $DRONE_COMMIT
  - name: build
    #    pull: if-not-exists
    environment:
      PATH: /root/go/bin
      GOROOT: /root/go
      GOPATH: /root/drone-go
      GOPROXY: https://goproxy.io
      GOPRIVATE: git.xiagaogao.com
      GOSUMDB: sum.golang.google.cn
    commands:
      - go build
      - go test
    when:
      branch:
        - master
        - feature/*
      event:
        - push
