

kind: pipeline
type: exec
name: build

platform:
  os: linux
  arch: amd64

workspace:
  base: /root/drone-go
  path: src/git.xiagaogao.com/coffee/boot

#clone:
#  disable: true
#  depth: 50

steps:
#  - name: clone
#    commands:
#      - git clone https://github.com/octocat/hello-world.git .
#      - git checkout $DRONE_COMMIT
  - name: build
    #    pull: if-not-exists
    environment:
      GOPROXY: https://goproxy.io
      GOPRIVATE: git.xiagaogao.com
      GOSUMDB: sum.golang.google.cn
      USERNAME:
        from_secret: username
      ACCESS_TOKEN:
        from_secret: access_token
    commands:
      - export PATH=$PATH:/root/go/bin
      - export GOROOT=/root/go
      - export GOPATH=/root/drone-go
      - git config --global url."https://$USERNAME:$ACCESS_TOKEN@git.xiagaogao.com.com".insteadOf "https://git.xiagaogao.com"
      - go build
      - go test
    when:
      branch:
        include:
          - feature/*
          - master
          - dev
      event:
        include:
          - push
          - pull_request
