// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: model.proto

package proxycodec

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type ProxyFrame struct {
	ServiceName          string   `protobuf:"bytes,1,opt,name=serviceName,proto3" json:"serviceName,omitempty"`
	Model                string   `protobuf:"bytes,2,opt,name=model,proto3" json:"model,omitempty"`
	Payload              []byte   `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProxyFrame) Reset()         { *m = ProxyFrame{} }
func (m *ProxyFrame) String() string { return proto.CompactTextString(m) }
func (*ProxyFrame) ProtoMessage()    {}
func (*ProxyFrame) Descriptor() ([]byte, []int) {
	return fileDescriptor_4c16552f9fdb66d8, []int{0}
}
func (m *ProxyFrame) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProxyFrame.Unmarshal(m, b)
}
func (m *ProxyFrame) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProxyFrame.Marshal(b, m, deterministic)
}
func (m *ProxyFrame) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProxyFrame.Merge(m, src)
}
func (m *ProxyFrame) XXX_Size() int {
	return xxx_messageInfo_ProxyFrame.Size(m)
}
func (m *ProxyFrame) XXX_DiscardUnknown() {
	xxx_messageInfo_ProxyFrame.DiscardUnknown(m)
}

var xxx_messageInfo_ProxyFrame proto.InternalMessageInfo

func (m *ProxyFrame) GetServiceName() string {
	if m != nil {
		return m.ServiceName
	}
	return ""
}

func (m *ProxyFrame) GetModel() string {
	if m != nil {
		return m.Model
	}
	return ""
}

func (m *ProxyFrame) GetPayload() []byte {
	if m != nil {
		return m.Payload
	}
	return nil
}

func init() {
	proto.RegisterType((*ProxyFrame)(nil), "grpcproxy.ProxyFrame")
}

func init() { proto.RegisterFile("model.proto", fileDescriptor_4c16552f9fdb66d8) }

var fileDescriptor_4c16552f9fdb66d8 = []byte{
	// 132 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xce, 0xcd, 0x4f, 0x49,
	0xcd, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x4c, 0x2f, 0x2a, 0x48, 0x2e, 0x28, 0xca,
	0xaf, 0xa8, 0x54, 0x8a, 0xe3, 0xe2, 0x0a, 0x00, 0x31, 0xdc, 0x8a, 0x12, 0x73, 0x53, 0x85, 0x14,
	0xb8, 0xb8, 0x8b, 0x53, 0x8b, 0xca, 0x32, 0x93, 0x53, 0xfd, 0x12, 0x73, 0x53, 0x25, 0x18, 0x15,
	0x18, 0x35, 0x38, 0x83, 0x90, 0x85, 0x84, 0x44, 0xb8, 0x58, 0xc1, 0x26, 0x49, 0x30, 0x81, 0xe5,
	0x20, 0x1c, 0x21, 0x09, 0x2e, 0xf6, 0x82, 0xc4, 0xca, 0x9c, 0xfc, 0xc4, 0x14, 0x09, 0x66, 0x05,
	0x46, 0x0d, 0x9e, 0x20, 0x18, 0xd7, 0x89, 0x27, 0x8a, 0x0b, 0x6c, 0x51, 0x72, 0x7e, 0x4a, 0x6a,
	0x72, 0x12, 0x1b, 0xd8, 0x7e, 0x63, 0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0xcf, 0x13, 0x1c, 0x13,
	0x8e, 0x00, 0x00, 0x00,
}
