package base

const (
	ERROR_CODE_BASE_SCOPE = 0x00000000
)

var (
	ERROR_CODE_BASE_INIT_ERROR int64 = ERROR_CODE_BASE_SCOPE | 0x1 //初始化失败
	ERROR_CODE_BASE_CONFIG_ERROR int64 = ERROR_CODE_BASE_SCOPE | 0x2 // 配置错误
	ERROR_CODE_BASE_SYSTEM_ERROR int64 = ERROR_CODE_BASE_SCOPE | 0x3 //系统错误
	ERROR_CODE_BASE_INVALID_PARAM int64 = ERROR_CODE_BASE_SCOPE | 0x4 //无效参数
	ERROR_CODE_BASE_ENCODE_ERROR int64 = ERROR_CODE_BASE_SCOPE | 0x5 //解码失败
	ERROR_CODE_BASE_DECODE_ERROR int64 = ERROR_CODE_BASE_SCOPE | 0x6 //解码失败
	ERROR_CODE_BASE_RESPONSE_API_ERROR int64 = ERROR_CODE_BASE_SCOPE | 0x7 //API请求错误
	ERROR_CODE_BASE_404 int64 = ERROR_CODE_BASE_SCOPE | 0x8 //找不到页面或者 Get 时候没有值
	ERROR_CODE_BASE_403 int64 = ERROR_CODE_BASE_SCOPE | 0x9 //没有权限
	ERROR_CODE_BASE_401 int64 = ERROR_CODE_BASE_SCOPE | 0xa //认证失败
	ERROR_CODE_BASE_API_REQUEST_BAD int64 = ERROR_CODE_BASE_SCOPE | 0xd //API请求异常
	ERROR_CODE_BASE_API_NOSUPPORT_CONTENTTYPE int64 = ERROR_CODE_BASE_SCOPE | 0xc //API请求异常
	ERROR_CODE_BASE_SERVICE_REGISTER_ERROR int64 = ERROR_CODE_BASE_SCOPE | 0xd //注册服务失败
	ERROR_CODE_BASE_TYPE_CONV_ERROR int64 = ERROR_CODE_BASE_SCOPE | 0xe // 类型转换错误
	ERROR_CODE_BASE_STORAGE_ERROR int64 = ERROR_CODE_BASE_SCOPE | 0xf // 类型转换错误
)
