package base

const (
	ERROR_CODE_BASE_SCOPE = 0x00000000
)

var (
	ERROR_CODE_BASE_SYSTEM_ERROR       int64 = ERROR_CODE_BASE_SCOPE | 0x1
	ERROR_CODE_BASE_INVALID_PARAMTER   int64 = ERROR_CODE_BASE_SCOPE | 0x2
	ERROR_CODE_BASE_DECODE_ERROR       int64 = ERROR_CODE_BASE_SCOPE | 0x3
	ERROR_CODE_BASE_RESPONSE_API_ERROR int64 = ERROR_CODE_BASE_SCOPE | 0x4
)
